// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct RouterProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for RouterProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = RouterProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        RouterProxyMethods { wrapped_tx: tx }
    }
}

pub struct RouterProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, To, Gas> RouterProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn get_pair<
        Arg0: ProxyArg<TokenIdentifier<Env::Api>>,
        Arg1: ProxyArg<TokenIdentifier<Env::Api>>,
    >(
        self,
        first_token_id: Arg0,
        second_token_id: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPair")
            .argument(&first_token_id)
            .argument(&second_token_id)
            .original_result()
    }

    pub fn multi_pair_swap<
        Arg0: ProxyArg<MultiValueEncoded<Env::Api, MultiValue4<ManagedAddress<Env::Api>, ManagedBuffer<Env::Api>, TokenIdentifier<Env::Api>, BigUint<Env::Api>>>>,
    >(
        self,
        swap_operations: Arg0,
    ) -> TxTypedCall<Env, From, To, (), Gas, ManagedVec<Env::Api, EsdtTokenPayment<Env::Api>>> {
        self.wrapped_tx
            .raw_call("multiPairSwap")
            .argument(&swap_operations)
            .original_result()
    }
}

#[type_abi]
#[derive(ManagedVecItem, TopEncode, TopDecode, PartialEq, Clone, NestedEncode, NestedDecode)]
pub struct PairContractMetadata<Api>
where
    Api: ManagedTypeApi,
{
    pub first_token_id: TokenIdentifier<Api>,
    pub second_token_id: TokenIdentifier<Api>,
    pub address: ManagedAddress<Api>,
}
