// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           32
// Async Callback:                       1
// Total number of exported functions:  35

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    lib
    (
        init => init
        upgrade => upgrade
        addAdmins => add_admins
        removeAdmins => remove_admins
        isAdmin => is_admin
        getAdmins => admins
        pause => pause
        unpause => unpause
        isPaused => is_paused
        getUsdcIdentifier => get_usdc_identifier
        getWegldIdentifier => get_wegld_identifier
        getXexchangeRouterScAddress => get_xexchange_router_sc_address
        getWrapperScAddress => get_wrapper_sc_address
        setBotAddress => set_bot_address
        buy => buy
        takeProfit => take_profit
        isBot => is_bot
        getBotAddress => bot_address
        setup => setup
        setToken => set_dca_token
        setMinAmountPerSwap => set_min_amount_per_swap
        addAllowedFrequencies => add_allowed_frequencies
        removeAllowedFrequencies => remove_allowed_frequencies
        setProfitFeePercentage => set_profit_fee_percentage
        setCustomSlippagePercentage => set_custom_slippage_percentage
        getSetup => get_setup
        createStrategy => create_strategy
        modifyStrategy => modify_strategy
        deleteStrategy => delete_strategy
        deposit => deposit
        withdraw => withdraw
        getStrategyTokenAttributes => get_strategy_token_attributes_view
        getAllStrategies => get_all_strategies
        getAllStrategiesOnlyNonces => get_all_strategies_only_nonces
    )
}

multiversx_sc_wasm_adapter::async_callback! { lib }
